<template>
  <div class="max-w-3xl mx-auto px-6 py-16">
    <h1 class="text-3xl font-bold text-charcoal mb-8">Terms of Service</h1>
    <div class="prose text-charcoal/80 space-y-6 text-sm leading-relaxed">
      <p><strong>Last updated:</strong> {{ new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' }) }}</p>

      <h2 class="text-lg font-semibold text-charcoal mt-8">1. Acceptance of Terms</h2>
      <p>By accessing or using LearnClaude.ai ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>

      <h2 class="text-lg font-semibold text-charcoal mt-8">2. Description of Service</h2>
      <p>LearnClaude.ai is an interactive learning platform that teaches users how to use Claude AI tools. The Service includes lesson content, AI-powered tutoring, and progress tracking. LearnClaude.ai is not affiliated with, endorsed by, or sponsored by Anthropic, PBC.</p>

      <h2 class="text-lg font-semibold text-charcoal mt-8">3. Accounts</h2>
      <p>You must provide a valid email address and password to create an account. You are responsible for maintaining the security of your account. You must be at least 13 years old to use the Service.</p>

      <h2 class="text-lg font-semibold text-charcoal mt-8">4. Payments and Subscriptions</h2>
      <p>Free accounts have access to a limited set of lessons. Paid plans (Pro Monthly, Pro Yearly, Lifetime) unlock all lessons and features. Payments are processed securely through Stripe. Subscriptions renew automatically unless canceled. You may cancel at any time through your account settings. Refunds are handled on a case-by-case basis within 7 days of purchase.</p>

      <h2 class="text-lg font-semibold text-charcoal mt-8">5. Lifetime Plan</h2>
      <p>The Lifetime plan is a one-time payment that grants permanent access to all current and future lessons. Lifetime plans are limited in quantity. Once purchased, Lifetime access cannot be transferred to another account.</p>

      <h2 class="text-lg font-semibold text-charcoal mt-8">6. AI Tutor</h2>
      <p>The AI tutor feature is powered by third-party AI services. Responses are generated by AI and may not always be accurate. The AI tutor is an educational tool, not a substitute for professional advice. We do not guarantee the availability or accuracy of AI-generated content.</p>

      <h2 class="text-lg font-semibold text-charcoal mt-8">7. Acceptable Use</h2>
      <p>You may not use the Service to: attempt to gain unauthorized access, abuse rate limits, share account credentials, redistribute lesson content, or use automated systems to access the Service without permission.</p>

      <h2 class="text-lg font-semibold text-charcoal mt-8">8. Intellectual Property</h2>
      <p>All lesson content, design, and code are owned by LearnClaude.ai. You may not copy, redistribute, or resell any content from the platform.</p>

      <h2 class="text-lg font-semibold text-charcoal mt-8">9. Limitation of Liability</h2>
      <p>The Service is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the Service, including but not limited to loss of data, business interruption, or any direct or indirect damages.</p>

      <h2 class="text-lg font-semibold text-charcoal mt-8">10. Changes to Terms</h2>
      <p>We may update these Terms at any time. Continued use of the Service constitutes acceptance of updated Terms. We will notify registered users of material changes via email.</p>

      <h2 class="text-lg font-semibold text-charcoal mt-8">11. Contact</h2>
      <p>Questions about these Terms? Contact us at support@learnclaudeai.com.</p>
    </div>
  </div>
</template>
